version: 2.1

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-14.27
    steps:
      - checkout
      - restore_cache:
          name: Restore Cached Dependencies
          keys:
            - cci-haskell-v1-{{ checksum "blog.cabal" }}-{{ checksum "stack.yaml" }}
            - cci-haskell-v1-{{ checksum "blog.cabal" }}
            - cci-haskell-v1-
      - run:
          name: Resolve Dependencies
          command: stack --no-terminal setup
      - run:
          name: Build Dependencies
          command: stack --no-terminal build -j1 --fast --dependencies-only
      - save_cache:
          name: Cache Dependencies
          key: cci-haskell-v1-{{ checksum "blog.cabal" }}-{{ checksum "stack.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"
      - run:
          name: Build
          command: stack --no-terminal build
      - run:
          name: Generate Site
          command: PROD=1 stack --no-terminal exec site build
      - persist_to_workspace:
          root: '/root/project/'
          paths: "_site/"

  prerender:
    docker:
      - image: circleci/node:12.16
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/
      - run:
          name: move-site
          command: mv /tmp/_site _site
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          keys:
            - cci-npm-v1-{{ checksum "mathjax-prerender/package.json" }}-{{ checksum "mathjax-prerender/package-lock.json" }}
            - cci-npm-v1-{{ checksum "mathjax-prerender/package.json" }}
            - cci-npm-v1
      - run:
          name: npm-install
          working_directory: mathjax-prerender
          command: npm install
      - save_cache:
          key: cci-npm-v1-{{ checksum "mathjax-prerender/package.json" }}-{{ checksum "mathjax-prerender/package-lock.json" }}
          paths:
            - mathjax-prerender/node_modules
      - run:
          name: prerender
          working_directory: mathjax-prerender
          command: node mathjax-prerender.js
      - persist_to_workspace:
          root: '/home/circleci/project/'
          paths: "_site/"

  publish:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout # Get CircleCI to populate SSH keys so that we trust GitHub
      - attach_workspace:
          at: /tmp/
      - run:
          name: Publish Site
          working_directory: /tmp/_site
          command: |
            git init
            git config user.name 'CircleCI'
            git config user.email 'job@circleci.com'
            git add .
            git commit -m "Update (`date '+%F %T %Z'`)"
            git remote add origin "git@github.com:thjread/thjread.github.io.git"
            git push --force origin master

workflows:
  version: 2

  build_and_publish:
    jobs:
      - build
      - prerender:
          requires:
            - build
      - publish:
          requires:
            - prerender
          filters:
            branches:
              only: master
